// Code generated by protoc-gen-monkeyc. DO NOT EDIT.
// source: preset_status.proto

using Toybox.Lang;
using Toybox.System;
using Toybox.StringUtil;
using ProtobufLib;

module OpenGopro {

// EnumFlatMode
module EnumFlatMode {
  const FLAT_MODE_UNKNOWN = -1;
  const FLAT_MODE_PLAYBACK = 4;
  const FLAT_MODE_SETUP = 5;
  const FLAT_MODE_VIDEO = 12;
  const FLAT_MODE_TIME_LAPSE_VIDEO = 13;
  const FLAT_MODE_LOOPING = 15;
  const FLAT_MODE_PHOTO_SINGLE = 16;
  const FLAT_MODE_PHOTO = 17;
  const FLAT_MODE_PHOTO_NIGHT = 18;
  const FLAT_MODE_PHOTO_BURST = 19;
  const FLAT_MODE_TIME_LAPSE_PHOTO = 20;
  const FLAT_MODE_NIGHT_LAPSE_PHOTO = 21;
  const FLAT_MODE_BROADCAST_RECORD = 22;
  const FLAT_MODE_BROADCAST_BROADCAST = 23;
  const FLAT_MODE_TIME_WARP_VIDEO = 24;
  const FLAT_MODE_LIVE_BURST = 25;
  const FLAT_MODE_NIGHT_LAPSE_VIDEO = 26;
  const FLAT_MODE_SLOMO = 27;
  const FLAT_MODE_IDLE = 28;
  const FLAT_MODE_VIDEO_STAR_TRAIL = 29;
  const FLAT_MODE_VIDEO_LIGHT_PAINTING = 30;
  const FLAT_MODE_VIDEO_LIGHT_TRAIL = 31;
  const FLAT_MODE_VIDEO_BURST_SLOMO = 32;
}

// EnumPresetGroup
module EnumPresetGroup {
  const PRESET_GROUP_ID_VIDEO = 1000;
  const PRESET_GROUP_ID_PHOTO = 1001;
  const PRESET_GROUP_ID_TIMELAPSE = 1002;
  const PRESET_GROUP_ID_GENERAL = 2000;
}

// EnumPresetGroupIcon
module EnumPresetGroupIcon {
  const PRESET_GROUP_VIDEO_ICON_ID = 0;
  const PRESET_GROUP_PHOTO_ICON_ID = 1;
  const PRESET_GROUP_TIMELAPSE_ICON_ID = 2;
  const PRESET_GROUP_LONG_BAT_VIDEO_ICON_ID = 3;
  const PRESET_GROUP_ENDURANCE_VIDEO_ICON_ID = 4;
  const PRESET_GROUP_MAX_VIDEO_ICON_ID = 5;
  const PRESET_GROUP_MAX_PHOTO_ICON_ID = 6;
  const PRESET_GROUP_MAX_TIMELAPSE_ICON_ID = 7;
  const PRESET_GROUP_ND_MOD_VIDEO_ICON_ID = 8;
  const PRESET_GROUP_ND_MOD_PHOTO_ICON_ID = 9;
  const PRESET_GROUP_ND_MOD_TIMELAPSE_ICON_ID = 10;
}

// EnumPresetIcon
module EnumPresetIcon {
  const PRESET_ICON_VIDEO = 0;
  const PRESET_ICON_ACTIVITY = 1;
  const PRESET_ICON_CINEMATIC = 2;
  const PRESET_ICON_PHOTO = 3;
  const PRESET_ICON_LIVE_BURST = 4;
  const PRESET_ICON_BURST = 5;
  const PRESET_ICON_PHOTO_NIGHT = 6;
  const PRESET_ICON_TIMEWARP = 7;
  const PRESET_ICON_TIMELAPSE = 8;
  const PRESET_ICON_NIGHTLAPSE = 9;
  const PRESET_ICON_SNAIL = 10;
  const PRESET_ICON_VIDEO_2 = 11;
  const PRESET_ICON_PHOTO_2 = 13;
  const PRESET_ICON_PANORAMA = 14;
  const PRESET_ICON_BURST_2 = 15;
  const PRESET_ICON_TIMEWARP_2 = 16;
  const PRESET_ICON_TIMELAPSE_2 = 17;
  const PRESET_ICON_CUSTOM = 18;
  const PRESET_ICON_AIR = 19;
  const PRESET_ICON_BIKE = 20;
  const PRESET_ICON_EPIC = 21;
  const PRESET_ICON_INDOOR = 22;
  const PRESET_ICON_MOTOR = 23;
  const PRESET_ICON_MOUNTED = 24;
  const PRESET_ICON_OUTDOOR = 25;
  const PRESET_ICON_POV = 26;
  const PRESET_ICON_SELFIE = 27;
  const PRESET_ICON_SKATE = 28;
  const PRESET_ICON_SNOW = 29;
  const PRESET_ICON_TRAIL = 30;
  const PRESET_ICON_TRAVEL = 31;
  const PRESET_ICON_WATER = 32;
  const PRESET_ICON_LOOPING = 33;
  const PRESET_ICON_STARS = 34;
  const PRESET_ICON_ACTION = 35;
  const PRESET_ICON_FOLLOW_CAM = 36;
  const PRESET_ICON_SURF = 37;
  const PRESET_ICON_CITY = 38;
  const PRESET_ICON_SHAKY = 39;
  const PRESET_ICON_CHESTY = 40;
  const PRESET_ICON_HELMET = 41;
  const PRESET_ICON_BITE = 42;
  const PRESET_ICON_CUSTOM_CINEMATIC = 43;
  const PRESET_ICON_VLOG = 44;
  const PRESET_ICON_FPV = 45;
  const PRESET_ICON_HDR = 46;
  const PRESET_ICON_LANDSCAPE = 47;
  const PRESET_ICON_LOG = 48;
  const PRESET_ICON_CUSTOM_SLOMO = 49;
  const PRESET_ICON_TRIPOD = 50;
  const PRESET_ICON_MAX_VIDEO = 55;
  const PRESET_ICON_MAX_PHOTO = 56;
  const PRESET_ICON_MAX_TIMEWARP = 57;
  const PRESET_ICON_BASIC = 58;
  const PRESET_ICON_ULTRA_SLO_MO = 59;
  const PRESET_ICON_STANDARD_ENDURANCE = 60;
  const PRESET_ICON_ACTIVITY_ENDURANCE = 61;
  const PRESET_ICON_CINEMATIC_ENDURANCE = 62;
  const PRESET_ICON_SLOMO_ENDURANCE = 63;
  const PRESET_ICON_STATIONARY_1 = 64;
  const PRESET_ICON_STATIONARY_2 = 65;
  const PRESET_ICON_STATIONARY_3 = 66;
  const PRESET_ICON_STATIONARY_4 = 67;
  const PRESET_ICON_SIMPLE_SUPER_PHOTO = 70;
  const PRESET_ICON_SIMPLE_NIGHT_PHOTO = 71;
  const PRESET_ICON_HIGHEST_QUALITY_VIDEO = 73;
  const PRESET_ICON_STANDARD_QUALITY_VIDEO = 74;
  const PRESET_ICON_BASIC_QUALITY_VIDEO = 75;
  const PRESET_ICON_STAR_TRAIL = 76;
  const PRESET_ICON_LIGHT_PAINTING = 77;
  const PRESET_ICON_LIGHT_TRAIL = 78;
  const PRESET_ICON_FULL_FRAME = 79;
  const PRESET_ICON_EASY_MAX_VIDEO = 80;
  const PRESET_ICON_EASY_MAX_PHOTO = 81;
  const PRESET_ICON_EASY_MAX_TIMEWARP = 82;
  const PRESET_ICON_EASY_MAX_STAR_TRAIL = 83;
  const PRESET_ICON_EASY_MAX_LIGHT_PAINTING = 84;
  const PRESET_ICON_EASY_MAX_LIGHT_TRAIL = 85;
  const PRESET_ICON_MAX_STAR_TRAIL = 89;
  const PRESET_ICON_MAX_LIGHT_PAINTING = 90;
  const PRESET_ICON_MAX_LIGHT_TRAIL = 91;
  const PRESET_ICON_EASY_STANDARD_PROFILE = 100;
  const PRESET_ICON_EASY_HDR_PROFILE = 101;
  const PRESET_ICON_BURST_SLOMO = 102;
  const PRESET_ICON_TIMELAPSE_PHOTO = 1000;
  const PRESET_ICON_NIGHTLAPSE_PHOTO = 1001;
}

// EnumPresetTitle
module EnumPresetTitle {
  const PRESET_TITLE_ACTIVITY = 0;
  const PRESET_TITLE_STANDARD = 1;
  const PRESET_TITLE_CINEMATIC = 2;
  const PRESET_TITLE_PHOTO = 3;
  const PRESET_TITLE_LIVE_BURST = 4;
  const PRESET_TITLE_BURST = 5;
  const PRESET_TITLE_NIGHT = 6;
  const PRESET_TITLE_TIME_WARP = 7;
  const PRESET_TITLE_TIME_LAPSE = 8;
  const PRESET_TITLE_NIGHT_LAPSE = 9;
  const PRESET_TITLE_VIDEO = 10;
  const PRESET_TITLE_SLOMO = 11;
  const PRESET_TITLE_PHOTO_2 = 13;
  const PRESET_TITLE_PANORAMA = 14;
  const PRESET_TITLE_TIME_WARP_2 = 16;
  const PRESET_TITLE_CUSTOM = 18;
  const PRESET_TITLE_AIR = 19;
  const PRESET_TITLE_BIKE = 20;
  const PRESET_TITLE_EPIC = 21;
  const PRESET_TITLE_INDOOR = 22;
  const PRESET_TITLE_MOTOR = 23;
  const PRESET_TITLE_MOUNTED = 24;
  const PRESET_TITLE_OUTDOOR = 25;
  const PRESET_TITLE_POV = 26;
  const PRESET_TITLE_SELFIE = 27;
  const PRESET_TITLE_SKATE = 28;
  const PRESET_TITLE_SNOW = 29;
  const PRESET_TITLE_TRAIL = 30;
  const PRESET_TITLE_TRAVEL = 31;
  const PRESET_TITLE_WATER = 32;
  const PRESET_TITLE_LOOPING = 33;
  const PRESET_TITLE_STARS = 34;
  const PRESET_TITLE_ACTION = 35;
  const PRESET_TITLE_FOLLOW_CAM = 36;
  const PRESET_TITLE_SURF = 37;
  const PRESET_TITLE_CITY = 38;
  const PRESET_TITLE_SHAKY = 39;
  const PRESET_TITLE_CHESTY = 40;
  const PRESET_TITLE_HELMET = 41;
  const PRESET_TITLE_BITE = 42;
  const PRESET_TITLE_CUSTOM_CINEMATIC = 43;
  const PRESET_TITLE_VLOG = 44;
  const PRESET_TITLE_FPV = 45;
  const PRESET_TITLE_HDR = 46;
  const PRESET_TITLE_LANDSCAPE = 47;
  const PRESET_TITLE_LOG = 48;
  const PRESET_TITLE_CUSTOM_SLOMO = 49;
  const PRESET_TITLE_TRIPOD = 50;
  const PRESET_TITLE_BASIC = 58;
  const PRESET_TITLE_ULTRA_SLO_MO = 59;
  const PRESET_TITLE_STANDARD_ENDURANCE = 60;
  const PRESET_TITLE_ACTIVITY_ENDURANCE = 61;
  const PRESET_TITLE_CINEMATIC_ENDURANCE = 62;
  const PRESET_TITLE_SLOMO_ENDURANCE = 63;
  const PRESET_TITLE_STATIONARY_1 = 64;
  const PRESET_TITLE_STATIONARY_2 = 65;
  const PRESET_TITLE_STATIONARY_3 = 66;
  const PRESET_TITLE_STATIONARY_4 = 67;
  const PRESET_TITLE_SIMPLE_VIDEO = 68;
  const PRESET_TITLE_SIMPLE_TIME_WARP = 69;
  const PRESET_TITLE_SIMPLE_SUPER_PHOTO = 70;
  const PRESET_TITLE_SIMPLE_NIGHT_PHOTO = 71;
  const PRESET_TITLE_SIMPLE_VIDEO_ENDURANCE = 72;
  const PRESET_TITLE_HIGHEST_QUALITY = 73;
  const PRESET_TITLE_EXTENDED_BATTERY = 74;
  const PRESET_TITLE_LONGEST_BATTERY = 75;
  const PRESET_TITLE_STAR_TRAIL = 76;
  const PRESET_TITLE_LIGHT_PAINTING = 77;
  const PRESET_TITLE_LIGHT_TRAIL = 78;
  const PRESET_TITLE_FULL_FRAME = 79;
  const PRESET_TITLE_STANDARD_QUALITY_VIDEO = 82;
  const PRESET_TITLE_BASIC_QUALITY_VIDEO = 83;
  const PRESET_TITLE_HIGHEST_QUALITY_VIDEO = 93;
  const PRESET_TITLE_USER_DEFINED_CUSTOM_NAME = 94;
  const PRESET_TITLE_EASY_STANDARD_PROFILE = 99;
  const PRESET_TITLE_EASY_HDR_PROFILE = 100;
  const PRESET_TITLE_BURST_SLOMO = 106;
  const PRESET_TITLE_4_3_VIDEO = 125;
  const PRESET_TITLE_16_9_VIDEO = 126;
  const PRESET_TITLE_16_9_SLOMO = 127;
  const PRESET_TITLE_TIME_LAPSE_VIDEO = 131;
  const PRESET_TITLE_TIME_LAPSE_PHOTO = 132;
  const PRESET_TITLE_NIGHT_LAPSE_VIDEO = 133;
  const PRESET_TITLE_NIGHT_LAPSE_PHOTO = 134;
}

class NotifyPresetStatus {
  var f1 as Lang.Array<PresetGroup>;

  function initialize() {
    f1 = [];
  }

  function decode(data as Lang.ByteArray or ProtobufLib.Decoder) as Void {
    var d = data instanceof ProtobufLib.Decoder ? data : new ProtobufLib.Decoder(data);
    f1 = [];
    while (d.remaining() > 0) {
      var tag = d.varint();
      var fieldNum = tag >> 3;
      var wireType = tag & 0x7;

      switch (fieldNum) {
        case 1:
          var msg1 = new PresetGroup();
          msg1.decode(d.subDecoder());
          f1.add(msg1);
          break;
        default:
          d.skipField(wireType);
      }
    }
  }

  function encode() as Lang.ByteArray {
    var buf = []b;
    for (var i = 0; i < f1.size(); i++) {
      ProtobufLib.encodeVarint(buf, 10);
      var msgBytes = f1[i].encode();
      ProtobufLib.encodeVarint(buf, msgBytes.size());
      buf.addAll(msgBytes);
    }
    return buf;
  }

  function getPresetGroupArray() as Lang.Array<PresetGroup> { return f1; }

  function setPresetGroupArray(v as Lang.Array<PresetGroup>) as Void { f1 = v; }
}

class Preset {
  var f1 as Lang.Number;
  var f2 as Lang.Number;
  var f3 as Lang.Number;
  var f4 as Lang.Number;
  var f5 as Lang.Boolean;
  var f6 as Lang.Number;
  var f7 as Lang.Array<PresetSetting>;
  var f8 as Lang.Boolean;
  var f9 as Lang.Boolean;
  var f10 as Lang.String;
  var f11 as Lang.Boolean;

  function initialize() {
    f1 = 0;
    f2 = 0;
    f3 = 0;
    f4 = 0;
    f5 = false;
    f6 = 0;
    f7 = [];
    f8 = false;
    f9 = false;
    f10 = "";
    f11 = false;
  }

  function decode(data as Lang.ByteArray or ProtobufLib.Decoder) as Void {
    var d = data instanceof ProtobufLib.Decoder ? data : new ProtobufLib.Decoder(data);
    f7 = [];
    while (d.remaining() > 0) {
      var tag = d.varint();
      var fieldNum = tag >> 3;
      var wireType = tag & 0x7;

      switch (fieldNum) {
        case 1:
          f1 = d.varint();
          break;
        case 2:
          f2 = d.varint();
          break;
        case 3:
          f3 = d.varint();
          break;
        case 4:
          f4 = d.varint();
          break;
        case 5:
          f5 = d.varint() != 0;
          break;
        case 6:
          f6 = d.varint();
          break;
        case 7:
          var msg7 = new PresetSetting();
          msg7.decode(d.subDecoder());
          f7.add(msg7);
          break;
        case 8:
          f8 = d.varint() != 0;
          break;
        case 9:
          f9 = d.varint() != 0;
          break;
        case 10:
          f10 = d.string();
          break;
        case 11:
          f11 = d.varint() != 0;
          break;
        default:
          d.skipField(wireType);
      }
    }
  }

  function encode() as Lang.ByteArray {
    var buf = []b;
    if (f1 != 0) {
      ProtobufLib.encodeVarint(buf, 8);
      ProtobufLib.encodeVarint(buf, f1);
    }
    if (f2 != 0) {
      ProtobufLib.encodeVarint(buf, 16);
      ProtobufLib.encodeVarint(buf, f2);
    }
    if (f3 != 0) {
      ProtobufLib.encodeVarint(buf, 24);
      ProtobufLib.encodeVarint(buf, f3);
    }
    if (f4 != 0) {
      ProtobufLib.encodeVarint(buf, 32);
      ProtobufLib.encodeVarint(buf, f4);
    }
    if (f5 != false) {
      ProtobufLib.encodeVarint(buf, 40);
      ProtobufLib.encodeVarint(buf, f5 ? 1 : 0);
    }
    if (f6 != 0) {
      ProtobufLib.encodeVarint(buf, 48);
      ProtobufLib.encodeVarint(buf, f6);
    }
    for (var i = 0; i < f7.size(); i++) {
      ProtobufLib.encodeVarint(buf, 58);
      var msgBytes = f7[i].encode();
      ProtobufLib.encodeVarint(buf, msgBytes.size());
      buf.addAll(msgBytes);
    }
    if (f8 != false) {
      ProtobufLib.encodeVarint(buf, 64);
      ProtobufLib.encodeVarint(buf, f8 ? 1 : 0);
    }
    if (f9 != false) {
      ProtobufLib.encodeVarint(buf, 72);
      ProtobufLib.encodeVarint(buf, f9 ? 1 : 0);
    }
    if (f10 != "") {
      ProtobufLib.encodeVarint(buf, 82);
      var bytes = StringUtil.convertEncodedString(f10, {:fromRepresentation => StringUtil.REPRESENTATION_STRING_PLAIN_TEXT, :toRepresentation => StringUtil.REPRESENTATION_BYTE_ARRAY, :encoding => StringUtil.CHAR_ENCODING_UTF8}) as Lang.ByteArray;
      ProtobufLib.encodeVarint(buf, bytes.size());
      buf.addAll(bytes);
    }
    if (f11 != false) {
      ProtobufLib.encodeVarint(buf, 88);
      ProtobufLib.encodeVarint(buf, f11 ? 1 : 0);
    }
    return buf;
  }

  function getId() as Lang.Number { return f1; }
  function getMode() as Lang.Number { return f2; }
  function getTitleId() as Lang.Number { return f3; }
  function getTitleNumber() as Lang.Number { return f4; }
  function getUserDefined() as Lang.Boolean { return f5; }
  function getIcon() as Lang.Number { return f6; }
  function getSettingArray() as Lang.Array<PresetSetting> { return f7; }
  function getIsModified() as Lang.Boolean { return f8; }
  function getIsFixed() as Lang.Boolean { return f9; }
  function getCustomName() as Lang.String { return f10; }
  function getIsVisible() as Lang.Boolean { return f11; }

  function setId(v as Lang.Number) as Void { f1 = v; }
  function setMode(v as Lang.Number) as Void { f2 = v; }
  function setTitleId(v as Lang.Number) as Void { f3 = v; }
  function setTitleNumber(v as Lang.Number) as Void { f4 = v; }
  function setUserDefined(v as Lang.Boolean) as Void { f5 = v; }
  function setIcon(v as Lang.Number) as Void { f6 = v; }
  function setSettingArray(v as Lang.Array<PresetSetting>) as Void { f7 = v; }
  function setIsModified(v as Lang.Boolean) as Void { f8 = v; }
  function setIsFixed(v as Lang.Boolean) as Void { f9 = v; }
  function setCustomName(v as Lang.String) as Void { f10 = v; }
  function setIsVisible(v as Lang.Boolean) as Void { f11 = v; }
}

class RequestCustomPresetUpdate {
  var f1 as Lang.Number;
  var f2 as Lang.String;
  var f3 as Lang.Number;

  function initialize() {
    f1 = 0;
    f2 = "";
    f3 = 0;
  }

  function decode(data as Lang.ByteArray or ProtobufLib.Decoder) as Void {
    var d = data instanceof ProtobufLib.Decoder ? data : new ProtobufLib.Decoder(data);
    while (d.remaining() > 0) {
      var tag = d.varint();
      var fieldNum = tag >> 3;
      var wireType = tag & 0x7;

      switch (fieldNum) {
        case 1:
          f1 = d.varint();
          break;
        case 2:
          f2 = d.string();
          break;
        case 3:
          f3 = d.varint();
          break;
        default:
          d.skipField(wireType);
      }
    }
  }

  function encode() as Lang.ByteArray {
    var buf = []b;
    if (f1 != 0) {
      ProtobufLib.encodeVarint(buf, 8);
      ProtobufLib.encodeVarint(buf, f1);
    }
    if (f2 != "") {
      ProtobufLib.encodeVarint(buf, 18);
      var bytes = StringUtil.convertEncodedString(f2, {:fromRepresentation => StringUtil.REPRESENTATION_STRING_PLAIN_TEXT, :toRepresentation => StringUtil.REPRESENTATION_BYTE_ARRAY, :encoding => StringUtil.CHAR_ENCODING_UTF8}) as Lang.ByteArray;
      ProtobufLib.encodeVarint(buf, bytes.size());
      buf.addAll(bytes);
    }
    if (f3 != 0) {
      ProtobufLib.encodeVarint(buf, 24);
      ProtobufLib.encodeVarint(buf, f3);
    }
    return buf;
  }

  function getTitleId() as Lang.Number { return f1; }
  function getCustomName() as Lang.String { return f2; }
  function getIconId() as Lang.Number { return f3; }

  function setTitleId(v as Lang.Number) as Void { f1 = v; }
  function setCustomName(v as Lang.String) as Void { f2 = v; }
  function setIconId(v as Lang.Number) as Void { f3 = v; }
}

class RequestPresetSetVisibility {
  var f1 as Lang.Number;
  var f2 as Lang.Boolean;

  function initialize() {
    f1 = 0;
    f2 = false;
  }

  function decode(data as Lang.ByteArray or ProtobufLib.Decoder) as Void {
    var d = data instanceof ProtobufLib.Decoder ? data : new ProtobufLib.Decoder(data);
    while (d.remaining() > 0) {
      var tag = d.varint();
      var fieldNum = tag >> 3;
      var wireType = tag & 0x7;

      switch (fieldNum) {
        case 1:
          f1 = d.varint();
          break;
        case 2:
          f2 = d.varint() != 0;
          break;
        default:
          d.skipField(wireType);
      }
    }
  }

  function encode() as Lang.ByteArray {
    var buf = []b;
    if (f1 != 0) {
      ProtobufLib.encodeVarint(buf, 8);
      ProtobufLib.encodeVarint(buf, f1);
    }
    if (f2 != false) {
      ProtobufLib.encodeVarint(buf, 16);
      ProtobufLib.encodeVarint(buf, f2 ? 1 : 0);
    }
    return buf;
  }

  function getId() as Lang.Number { return f1; }
  function getVisible() as Lang.Boolean { return f2; }

  function setId(v as Lang.Number) as Void { f1 = v; }
  function setVisible(v as Lang.Boolean) as Void { f2 = v; }
}

class PresetGroup {
  var f1 as Lang.Number;
  var f2 as Lang.Array<Preset>;
  var f3 as Lang.Boolean;
  var f4 as Lang.Number;
  var f5 as Lang.Array<Lang.Number>;
  var f6 as Lang.String;
  var f7 as Lang.Number;

  function initialize() {
    f1 = 0;
    f2 = [];
    f3 = false;
    f4 = 0;
    f5 = [];
    f6 = "";
    f7 = 0;
  }

  function decode(data as Lang.ByteArray or ProtobufLib.Decoder) as Void {
    var d = data instanceof ProtobufLib.Decoder ? data : new ProtobufLib.Decoder(data);
    f2 = [];
    f5 = [];
    while (d.remaining() > 0) {
      var tag = d.varint();
      var fieldNum = tag >> 3;
      var wireType = tag & 0x7;

      switch (fieldNum) {
        case 1:
          f1 = d.varint();
          break;
        case 2:
          var msg2 = new Preset();
          msg2.decode(d.subDecoder());
          f2.add(msg2);
          break;
        case 3:
          f3 = d.varint() != 0;
          break;
        case 4:
          f4 = d.varint();
          break;
        case 5:
          if (wireType == 2) {
            var sub5 = d.subDecoder();
            while (sub5.remaining() > 0) {
              f5.add(sub5.varint());
            }
          } else {
            f5.add(d.varint());
          }
          break;
        case 6:
          f6 = d.string();
          break;
        case 7:
          f7 = d.varint();
          break;
        default:
          d.skipField(wireType);
      }
    }
  }

  function encode() as Lang.ByteArray {
    var buf = []b;
    if (f1 != 0) {
      ProtobufLib.encodeVarint(buf, 8);
      ProtobufLib.encodeVarint(buf, f1);
    }
    for (var i = 0; i < f2.size(); i++) {
      ProtobufLib.encodeVarint(buf, 18);
      var msgBytes = f2[i].encode();
      ProtobufLib.encodeVarint(buf, msgBytes.size());
      buf.addAll(msgBytes);
    }
    if (f3 != false) {
      ProtobufLib.encodeVarint(buf, 24);
      ProtobufLib.encodeVarint(buf, f3 ? 1 : 0);
    }
    if (f4 != 0) {
      ProtobufLib.encodeVarint(buf, 32);
      ProtobufLib.encodeVarint(buf, f4);
    }
    for (var i = 0; i < f5.size(); i++) {
      ProtobufLib.encodeVarint(buf, 40);
      ProtobufLib.encodeVarint(buf, f5[i]);
    }
    if (f6 != "") {
      ProtobufLib.encodeVarint(buf, 50);
      var bytes = StringUtil.convertEncodedString(f6, {:fromRepresentation => StringUtil.REPRESENTATION_STRING_PLAIN_TEXT, :toRepresentation => StringUtil.REPRESENTATION_BYTE_ARRAY, :encoding => StringUtil.CHAR_ENCODING_UTF8}) as Lang.ByteArray;
      ProtobufLib.encodeVarint(buf, bytes.size());
      buf.addAll(bytes);
    }
    if (f7 != 0) {
      ProtobufLib.encodeVarint(buf, 56);
      ProtobufLib.encodeVarint(buf, f7);
    }
    return buf;
  }

  function getId() as Lang.Number { return f1; }
  function getPresetArray() as Lang.Array<Preset> { return f2; }
  function getCanAddPreset() as Lang.Boolean { return f3; }
  function getIcon() as Lang.Number { return f4; }
  function getModeArray() as Lang.Array<Lang.Number> { return f5; }
  function getCustomName() as Lang.String { return f6; }
  function getActivePresetId() as Lang.Number { return f7; }

  function setId(v as Lang.Number) as Void { f1 = v; }
  function setPresetArray(v as Lang.Array<Preset>) as Void { f2 = v; }
  function setCanAddPreset(v as Lang.Boolean) as Void { f3 = v; }
  function setIcon(v as Lang.Number) as Void { f4 = v; }
  function setModeArray(v as Lang.Array<Lang.Number>) as Void { f5 = v; }
  function setCustomName(v as Lang.String) as Void { f6 = v; }
  function setActivePresetId(v as Lang.Number) as Void { f7 = v; }
}

class PresetSetting {
  var f1 as Lang.Number;
  var f2 as Lang.Number;
  var f3 as Lang.Boolean;

  function initialize() {
    f1 = 0;
    f2 = 0;
    f3 = false;
  }

  function decode(data as Lang.ByteArray or ProtobufLib.Decoder) as Void {
    var d = data instanceof ProtobufLib.Decoder ? data : new ProtobufLib.Decoder(data);
    while (d.remaining() > 0) {
      var tag = d.varint();
      var fieldNum = tag >> 3;
      var wireType = tag & 0x7;

      switch (fieldNum) {
        case 1:
          f1 = d.varint();
          break;
        case 2:
          f2 = d.varint();
          break;
        case 3:
          f3 = d.varint() != 0;
          break;
        default:
          d.skipField(wireType);
      }
    }
  }

  function encode() as Lang.ByteArray {
    var buf = []b;
    if (f1 != 0) {
      ProtobufLib.encodeVarint(buf, 8);
      ProtobufLib.encodeVarint(buf, f1);
    }
    if (f2 != 0) {
      ProtobufLib.encodeVarint(buf, 16);
      ProtobufLib.encodeVarint(buf, f2);
    }
    if (f3 != false) {
      ProtobufLib.encodeVarint(buf, 24);
      ProtobufLib.encodeVarint(buf, f3 ? 1 : 0);
    }
    return buf;
  }

  function getId() as Lang.Number { return f1; }
  function getValue() as Lang.Number { return f2; }
  function getIsCaption() as Lang.Boolean { return f3; }

  function setId(v as Lang.Number) as Void { f1 = v; }
  function setValue(v as Lang.Number) as Void { f2 = v; }
  function setIsCaption(v as Lang.Boolean) as Void { f3 = v; }
}

}
