// Originally generated by protoc-gen-monkeyc.
// Hand-optimized 2026-05 for memory:
//   - Decode signature now accepts a Protobuf.Decoder (zero-copy nesting)
//   - Encode uses Protobuf.appendField* (no intermediate ByteArrays)
//   - Repeated-field arrays reset at start of every Decode
//   - All debug println / debugPosition calls removed
//   - Unused getter methods and module-level EnumValue dictionaries removed
// Regenerating with the upstream generator will revert these changes —
// either preserve this file or port the same optimizations to the generator.

import Toybox.Lang;

class ResponseGeneric {
    public var result as ERG;

    public function initialize() {
        result = 0;
    }

    public function Encode() as ByteArray {
        var buf = []b;
        Protobuf.appendFieldVarint(buf, 1, result, false);
        return buf;
    }

    public function Decode(d as Protobuf.Decoder) as Void {
        while (d.remaining() > 0) {
            var tag = d.varint32();
            switch (tag >> 3) {
                case 1: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    result = d.varint32() as ERG;
                    break;
                }
            }
        }
    }
}

class Media {
    public var folder as String;
    public var file as String;

    public function initialize() {
        folder = "";
        file = "";
    }

    public function Encode() as ByteArray {
        var buf = []b;
        Protobuf.appendFieldLen(buf, 1, folder, false);
        Protobuf.appendFieldLen(buf, 2, file, false);
        return buf;
    }

    public function Decode(d as Protobuf.Decoder) as Void {
        while (d.remaining() > 0) {
            var tag = d.varint32();
            switch (tag >> 3) {
                case 1: {
                    Protobuf.assertWireType(tag, Protobuf.LEN);
                    folder = d.string();
                    break;
                }
                case 2: {
                    Protobuf.assertWireType(tag, Protobuf.LEN);
                    file = d.string();
                    break;
                }
            }
        }
    }
}

enum ERG { ERG_U = 0, ERG_S = 1, ERG_IF = 2, ERG_NS = 3, ERG_OB = 4, ERG_IV = 5, ERG_NA = 6 }

class NotifyPresetStatus {
    public var presetGroupArray as Array<PresetGroup>;

    public function initialize() {
        presetGroupArray = [];
    }

    public function Encode() as ByteArray {
        var buf = []b;
        for (var i = 0; i < presetGroupArray.size(); i++) {
            Protobuf.appendFieldLen(buf, 1, presetGroupArray[i].Encode(), true);
        }
        return buf;
    }

    public function Decode(d as Protobuf.Decoder) as Void {
        presetGroupArray = [];
        while (d.remaining() > 0) {
            var tag = d.varint32();
            switch (tag >> 3) {
                case 1: {
                    Protobuf.assertWireType(tag, Protobuf.LEN);
                    var msg = new PresetGroup();
                    msg.Decode(d.subDecoder());
                    presetGroupArray.add(msg);
                    break;
                }
                default: {
                    // Skip unknown fields based on wire type.
                    var wireType = tag & 7;
                    if (wireType == Protobuf.VARINT) {
                        d.varint32();
                    } else if (wireType == Protobuf.LEN) {
                        d.data();
                    } else if (wireType == Protobuf.I32) {
                        d.number();
                    } else if (wireType == Protobuf.I64) {
                        d.long();
                    } else {
                        d.data();
                    }
                    break;
                }
            }
        }
    }
}

class Preset {
    public var id as Number;
    public var mode as EFM;
    public var titleId as EPT;
    public var titleNumber as Number;
    public var userDefined as Boolean;
    public var icon as EPI;
    public var settingArray as Array<PresetSetting>;
    public var isModified as Boolean;
    public var isFixed as Boolean;
    public var customName as String;

    public function initialize() {
        id = 0;
        mode = 0;
        titleId = 0;
        titleNumber = 0;
        userDefined = false;
        icon = 0;
        settingArray = [];
        isModified = false;
        isFixed = false;
        customName = "";
    }

    public function Encode() as ByteArray {
        var buf = []b;
        Protobuf.appendFieldVarint(buf, 1, id, false);
        Protobuf.appendFieldVarint(buf, 2, mode, false);
        Protobuf.appendFieldVarint(buf, 3, titleId, false);
        Protobuf.appendFieldVarint(buf, 4, titleNumber, false);
        Protobuf.appendFieldVarint(buf, 5, userDefined, false);
        Protobuf.appendFieldVarint(buf, 6, icon, false);
        for (var i = 0; i < settingArray.size(); i++) {
            Protobuf.appendFieldLen(buf, 7, settingArray[i].Encode(), true);
        }
        Protobuf.appendFieldVarint(buf, 8, isModified, false);
        Protobuf.appendFieldVarint(buf, 9, isFixed, false);
        Protobuf.appendFieldLen(buf, 10, customName, false);
        return buf;
    }

    public function Decode(d as Protobuf.Decoder) as Void {
        settingArray = [];
        while (d.remaining() > 0) {
            var tag = d.varint32();
            switch (tag >> 3) {
                case 1: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    id = d.varint32();
                    break;
                }
                case 2: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    mode = d.varint32() as EFM;
                    break;
                }
                case 3: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    titleId = d.varint32() as EPT;
                    break;
                }
                case 4: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    titleNumber = d.varint32();
                    break;
                }
                case 5: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    userDefined = d.varint32() != 0;
                    break;
                }
                case 6: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    icon = d.varint32() as EPI;
                    break;
                }
                case 7: {
                    Protobuf.assertWireType(tag, Protobuf.LEN);
                    var msg = new PresetSetting();
                    msg.Decode(d.subDecoder());
                    settingArray.add(msg);
                    break;
                }
                case 8: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    isModified = d.varint32() != 0;
                    break;
                }
                case 9: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    isFixed = d.varint32() != 0;
                    break;
                }
                case 10: {
                    Protobuf.assertWireType(tag, Protobuf.LEN);
                    customName = d.string();
                    break;
                }
            }
        }
    }
}

class RequestCustomPresetUpdate {
    public var titleId as EPT;
    public var customName as String;
    public var iconId as EPI;

    public function initialize() {
        titleId = 0;
        customName = "";
        iconId = 0;
    }

    public function Encode() as ByteArray {
        var buf = []b;
        Protobuf.appendFieldVarint(buf, 1, titleId, false);
        Protobuf.appendFieldLen(buf, 2, customName, false);
        Protobuf.appendFieldVarint(buf, 3, iconId, false);
        return buf;
    }

    public function Decode(d as Protobuf.Decoder) as Void {
        while (d.remaining() > 0) {
            var tag = d.varint32();
            switch (tag >> 3) {
                case 1: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    titleId = d.varint32() as EPT;
                    break;
                }
                case 2: {
                    Protobuf.assertWireType(tag, Protobuf.LEN);
                    customName = d.string();
                    break;
                }
                case 3: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    iconId = d.varint32() as EPI;
                    break;
                }
            }
        }
    }
}

class PresetGroup {
    public var id as EPG;
    public var presetArray as Array<Preset>;
    public var canAddPreset as Boolean;
    public var icon as EPGI;
    public var modeArray as Array<EFM>;

    public function initialize() {
        id = 0;
        presetArray = [];
        canAddPreset = false;
        icon = 0;
        modeArray = [];
    }

    public function Encode() as ByteArray {
        var buf = []b;
        Protobuf.appendFieldVarint(buf, 1, id, false);
        for (var i = 0; i < presetArray.size(); i++) {
            Protobuf.appendFieldLen(buf, 2, presetArray[i].Encode(), true);
        }
        Protobuf.appendFieldVarint(buf, 3, canAddPreset, false);
        Protobuf.appendFieldVarint(buf, 4, icon, false);
        if (modeArray.size() > 0) {
            var packed = []b;
            for (var i = 0; i < modeArray.size(); i++) {
                Protobuf.appendVarint(packed, modeArray[i]);
            }
            Protobuf.appendFieldLen(buf, 5, packed, false);
        }
        return buf;
    }

    public function Decode(d as Protobuf.Decoder) as Void {
        presetArray = [];
        modeArray = [];
        while (d.remaining() > 0) {
            var tag = d.varint32();
            switch (tag >> 3) {
                case 1: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    id = d.varint32() as EPG;
                    break;
                }
                case 2: {
                    Protobuf.assertWireType(tag, Protobuf.LEN);
                    var msg = new Preset();
                    msg.Decode(d.subDecoder());
                    presetArray.add(msg);
                    break;
                }
                case 3: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    canAddPreset = d.varint32() != 0;
                    break;
                }
                case 4: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    icon = d.varint32() as EPGI;
                    break;
                }
                case 5: {
                    switch (tag & 7) {
                        case Protobuf.VARINT:
                            modeArray.add(d.varint32() as EFM);
                            break;
                        case Protobuf.LEN:
                            var sub = d.subDecoder();
                            while (sub.remaining() > 0) {
                                modeArray.add(sub.varint32() as EFM);
                            }
                            break;
                        default:
                            throw new Protobuf.Exception("invalid wire type");
                    }
                    break;
                }
            }
        }
    }
}

class PresetSetting {
    public var id as Number;
    public var value as Number;
    public var isCaption as Boolean;

    public function initialize() {
        id = 0;
        value = 0;
        isCaption = false;
    }

    public function Encode() as ByteArray {
        var buf = []b;
        Protobuf.appendFieldVarint(buf, 1, id, false);
        Protobuf.appendFieldVarint(buf, 2, value, false);
        Protobuf.appendFieldVarint(buf, 3, isCaption, false);
        return buf;
    }

    public function Decode(d as Protobuf.Decoder) as Void {
        while (d.remaining() > 0) {
            var tag = d.varint32();
            switch (tag >> 3) {
                case 1: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    id = d.varint32();
                    break;
                }
                case 2: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    value = d.varint32();
                    break;
                }
                case 3: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    isCaption = d.varint32() != 0;
                    break;
                }
            }
        }
    }
}

enum EFM { EFM_U = -1, EFM_PB = 4, EFM_ST = 5, EFM_V = 12, EFM_TLV = 13, EFM_L = 15, EFM_PS = 16, EFM_PH = 17, EFM_PN = 18, EFM_PB2 = 19, EFM_TLP = 20, EFM_NLP = 21, EFM_BR = 22, EFM_BB = 23, EFM_TWV = 24, EFM_LB = 25, EFM_NLV = 26, EFM_SM = 27, EFM_ID = 28, EFM_VS = 29, EFM_VL = 30, EFM_LT = 31, EFM_BS = 32 }

enum EPG { EPG_V = 1000, EPG_P = 1001, EPG_T = 1002 }

enum EPGI { EPGI_V = 0, EPGI_P = 1, EPGI_T = 2 }

enum EPI { EPI_V = 0, EPI_A = 1, EPI_C = 2, EPI_PH = 3, EPI_LB = 4, EPI_BU = 5, EPI_PN = 6, EPI_TW = 7, EPI_TL = 8, EPI_NL = 9, EPI_SN = 10, EPI_V2 = 11, EPI_P2 = 13, EPI_PA = 14, EPI_B2 = 15, EPI_TW2 = 16, EPI_CU = 18, EPI_AR = 19, EPI_BK = 20, EPI_EP = 21, EPI_IN = 22, EPI_MO = 23, EPI_MT = 24, EPI_OD = 25, EPI_PV = 26, EPI_SF = 27, EPI_SK = 28, EPI_SN2 = 29, EPI_TR = 30, EPI_TV = 31, EPI_WT = 32, EPI_LO = 33, EPI_ST = 34, EPI_AC2 = 35, EPI_FC = 36, EPI_SU = 37, EPI_CT = 38, EPI_SH = 39, EPI_CH = 40, EPI_HE = 41, EPI_BI = 42, EPI_CC = 43, EPI_VL = 44, EPI_FP = 45, EPI_HD = 46, EPI_LA = 47, EPI_LG = 48, EPI_CS = 49, EPI_TP = 50, EPI_MV2 = 55, EPI_MP2 = 56, EPI_MT2 = 57, EPI_BC = 58, EPI_US = 59, EPI_SE = 60, EPI_AE = 61, EPI_CE = 62, EPI_SO = 63, EPI_S1 = 64, EPI_S2 = 65, EPI_S3 = 66, EPI_S4 = 67, EPI_SSP = 70, EPI_SNP = 71, EPI_HQV = 73, EPI_EMP = 74, EPI_LOB = 75, EPI_STR = 76, EPI_LPA = 77, EPI_LTR = 78, EPI_FF = 79, EPI_EMV = 80, EPI_EMP2 = 81, EPI_EMT = 82, EPI_EMS = 83, EPI_EMA = 84, EPI_EML = 85, EPI_MST = 89, EPI_MLP = 90, EPI_MLT = 91, EPI_ESP = 100, EPI_EHP = 101, EPI_BS2 = 102, EPI_TPP = 1000, EPI_NLP = 1001 }

enum EPT { EPT_AC = 0, EPT_ST = 1, EPT_CI = 2, EPT_PH = 3, EPT_LB = 4, EPT_BU = 5, EPT_NI = 6, EPT_TW = 7, EPT_TL = 8, EPT_NL = 9, EPT_VI = 10, EPT_SM = 11, EPT_P2 = 13, EPT_PA = 14, EPT_TW2 = 16, EPT_CU = 18, EPT_AR = 19, EPT_BK = 20, EPT_EP = 21, EPT_IN = 22, EPT_MO = 23, EPT_MT = 24, EPT_OD = 25, EPT_PV = 26, EPT_SF = 27, EPT_SK = 28, EPT_SN = 29, EPT_TR = 30, EPT_TV = 31, EPT_WT = 32, EPT_LO = 33, EPT_ST2 = 34, EPT_AC2 = 35, EPT_FC = 36, EPT_SU = 37, EPT_CT = 38, EPT_SH = 39, EPT_CH = 40, EPT_HE = 41, EPT_BI = 42, EPT_CC = 43, EPT_VL = 44, EPT_FP = 45, EPT_HD = 46, EPT_LA = 47, EPT_LG = 48, EPT_CS = 49, EPT_TP = 50, EPT_BC = 58, EPT_US = 59, EPT_SE = 60, EPT_AE = 61, EPT_CE = 62, EPT_SO = 63, EPT_S1 = 64, EPT_S2 = 65, EPT_S3 = 66, EPT_S4 = 67, EPT_SV = 68, EPT_STW = 69, EPT_SSP = 70, EPT_SNP = 71, EPT_SVE = 72, EPT_HQ = 73, EPT_EB = 74, EPT_LB2 = 75, EPT_STR = 76, EPT_LPA = 77, EPT_LTR = 78, EPT_FF = 79, EPT_SQV = 82, EPT_BQV = 83, EPT_HQV = 93, EPT_UDCN = 94, EPT_ESP = 99, EPT_EHP = 100, EPT_BS2 = 106, EPT_V43 = 125, EPT_V169 = 126, EPT_S169 = 127 }
