// Code generated by protoc-gen-monkeyc. DO NOT EDIT.
// source: request_get_preset_status.proto

using Toybox.Lang;
using Toybox.System;
using Toybox.StringUtil;
using ProtobufLib;

module OpenGopro {

// EnumRegisterPresetStatus
module EnumRegisterPresetStatus {
  const REGISTER_PRESET_STATUS_PRESET = 1;
  const REGISTER_PRESET_STATUS_PRESET_GROUP_ARRAY = 2;
}

class RequestGetPresetStatus {
  var f1;
  var f2;
  var f3;
  var f4;

  function initialize() {
    f1 = [];
    f2 = [];
    f3 = false;
    f4 = false;
  }

  function decode(data) {
    var d = data instanceof ProtobufLib.Decoder ? data : new ProtobufLib.Decoder(data);
    f1 = [];
    f2 = [];
    while (d.remaining() > 0) {
      var tag = d.varint();
      var fieldNum = tag >> 3;
      var wireType = tag & 0x7;

      switch (fieldNum) {
        case 1:
          if (wireType == 2) {
            var sub1 = d.subDecoder();
            while (sub1.remaining() > 0) {
              f1.add(sub1.varint());
            }
          } else {
            f1.add(d.varint());
          }
          break;
        case 2:
          if (wireType == 2) {
            var sub2 = d.subDecoder();
            while (sub2.remaining() > 0) {
              f2.add(sub2.varint());
            }
          } else {
            f2.add(d.varint());
          }
          break;
        case 3:
          f3 = d.varint() != 0;
          break;
        case 4:
          f4 = d.varint() != 0;
          break;
        default:
          d.skipField(wireType);
      }
    }
  }

  function encode() {
    var buf = []b;
    for (var i = 0; i < f1.size(); i++) {
      ProtobufLib.encodeVarint(buf, 8);
      ProtobufLib.encodeVarint(buf, f1[i]);
    }
    for (var i = 0; i < f2.size(); i++) {
      ProtobufLib.encodeVarint(buf, 16);
      ProtobufLib.encodeVarint(buf, f2[i]);
    }
    if (f3 != false) {
      ProtobufLib.encodeVarint(buf, 24);
      ProtobufLib.encodeVarint(buf, f3 ? 1 : 0);
    }
    if (f4 != false) {
      ProtobufLib.encodeVarint(buf, 32);
      ProtobufLib.encodeVarint(buf, f4 ? 1 : 0);
    }
    return buf;
  }

  function getRegisterPresetStatus() { return f1; }
  function getUnregisterPresetStatus() { return f2; }
  function getUseConstantSettingIds() { return f3; }
  function getIncludeHidden() { return f4; }

  function setRegisterPresetStatus(v) { f1 = v; }
  function setUnregisterPresetStatus(v) { f2 = v; }
  function setUseConstantSettingIds(v) { f3 = v; }
  function setIncludeHidden(v) { f4 = v; }
}

}
