// Originally generated by protoc-gen-monkeyc.
// Hand-optimized 2026-05 alongside preset_status.pb.mc — see notes there.

import Toybox.Lang;

class RequestGetPresetStatus {
    public var registerPresetStatus as Array<ERPS>;
    public var unregisterPresetStatus as Array<ERPS>;
    public var useConstantSettingIds as Boolean;

    public function initialize() {
        registerPresetStatus = [];
        unregisterPresetStatus = [];
        useConstantSettingIds = false;
    }

    public function Encode() as ByteArray {
        var buf = []b;
        if (registerPresetStatus.size() > 0) {
            var packed = []b;
            for (var i = 0; i < registerPresetStatus.size(); i++) {
                Protobuf.appendVarint(packed, registerPresetStatus[i]);
            }
            Protobuf.appendFieldLen(buf, 1, packed, false);
        }
        if (unregisterPresetStatus.size() > 0) {
            var packed = []b;
            for (var i = 0; i < unregisterPresetStatus.size(); i++) {
                Protobuf.appendVarint(packed, unregisterPresetStatus[i]);
            }
            Protobuf.appendFieldLen(buf, 2, packed, false);
        }
        Protobuf.appendFieldVarint(buf, 3, useConstantSettingIds, false);
        return buf;
    }

    public function Decode(d as Protobuf.Decoder) as Void {
        registerPresetStatus = [];
        unregisterPresetStatus = [];
        while (d.remaining() > 0) {
            var tag = d.varint32();
            switch (tag >> 3) {
                case 1: {
                    switch (tag & 7) {
                        case Protobuf.VARINT:
                            registerPresetStatus.add(d.varint32() as ERPS);
                            break;
                        case Protobuf.LEN:
                            var sub = d.subDecoder();
                            while (sub.remaining() > 0) {
                                registerPresetStatus.add(sub.varint32() as ERPS);
                            }
                            break;
                        default:
                            throw new Protobuf.Exception("invalid wire type");
                    }
                    break;
                }
                case 2: {
                    switch (tag & 7) {
                        case Protobuf.VARINT:
                            unregisterPresetStatus.add(d.varint32() as ERPS);
                            break;
                        case Protobuf.LEN:
                            var sub = d.subDecoder();
                            while (sub.remaining() > 0) {
                                unregisterPresetStatus.add(sub.varint32() as ERPS);
                            }
                            break;
                        default:
                            throw new Protobuf.Exception("invalid wire type");
                    }
                    break;
                }
                case 3: {
                    Protobuf.assertWireType(tag, Protobuf.VARINT);
                    useConstantSettingIds = d.varint32() != 0;
                    break;
                }
            }
        }
    }
}

enum ERPS {
    ERPS_P = 1,
    ERPS_PGA = 2,
}
