// Code generated by protoc-gen-monkeyc. DO NOT EDIT.
// source: response_generic.proto

using Toybox.Lang;
using Toybox.System;
using Toybox.StringUtil;
using ProtobufLib;

module OpenGopro {

// EnumResultGeneric
module EnumResultGeneric {
  const RESULT_UNKNOWN = 0;
  const RESULT_SUCCESS = 1;
  const RESULT_ILL_FORMED = 2;
  const RESULT_NOT_SUPPORTED = 3;
  const RESULT_ARGUMENT_OUT_OF_BOUNDS = 4;
  const RESULT_ARGUMENT_INVALID = 5;
  const RESULT_RESOURCE_NOT_AVAILABLE = 6;
}

class ResponseGeneric {
  var f1;

  function initialize() {
    f1 = 0;
  }

  function decode(data) {
    var d = data instanceof ProtobufLib.Decoder ? data : new ProtobufLib.Decoder(data);
    while (d.remaining() > 0) {
      var tag = d.varint();
      var fieldNum = tag >> 3;
      var wireType = tag & 0x7;

      switch (fieldNum) {
        case 1:
          f1 = d.varint();
          break;
        default:
          d.skipField(wireType);
      }
    }
  }

  function encode() {
    var buf = []b;
    if (f1 != 0) {
      ProtobufLib.encodeVarint(buf, 8);
      ProtobufLib.encodeVarint(buf, f1);
    }
    return buf;
  }

  function getResult() { return f1; }

  function setResult(v) { f1 = v; }
}

class Media {
  var f1;
  var f2;

  function initialize() {
    f1 = "";
    f2 = "";
  }

  function decode(data) {
    var d = data instanceof ProtobufLib.Decoder ? data : new ProtobufLib.Decoder(data);
    while (d.remaining() > 0) {
      var tag = d.varint();
      var fieldNum = tag >> 3;
      var wireType = tag & 0x7;

      switch (fieldNum) {
        case 1:
          f1 = d.string();
          break;
        case 2:
          f2 = d.string();
          break;
        default:
          d.skipField(wireType);
      }
    }
  }

  function encode() {
    var buf = []b;
    if (f1 != "") {
      ProtobufLib.encodeVarint(buf, 10);
      var bytes = StringUtil.convertEncodedString(f1, {:fromRepresentation => StringUtil.REPRESENTATION_STRING_PLAIN_TEXT, :toRepresentation => StringUtil.REPRESENTATION_BYTE_ARRAY, :encoding => StringUtil.CHAR_ENCODING_UTF8});
      ProtobufLib.encodeVarint(buf, bytes.size());
      buf.addAll(bytes);
    }
    if (f2 != "") {
      ProtobufLib.encodeVarint(buf, 18);
      var bytes = StringUtil.convertEncodedString(f2, {:fromRepresentation => StringUtil.REPRESENTATION_STRING_PLAIN_TEXT, :toRepresentation => StringUtil.REPRESENTATION_BYTE_ARRAY, :encoding => StringUtil.CHAR_ENCODING_UTF8});
      ProtobufLib.encodeVarint(buf, bytes.size());
      buf.addAll(bytes);
    }
    return buf;
  }

  function getFolder() { return f1; }
  function getFile() { return f2; }

  function setFolder(v) { f1 = v; }
  function setFile(v) { f2 = v; }
}

}
